version: "3.1"

services:
  ofcar:
    build:
      args:
        container_project_path: /var/www/html/
        uid: 1000
        user: root
      context: .
      dockerfile: ./Dockerfile
    image: ircarvalho-php-apache
    ports:
      - 8080:80
    volumes:
      - ./workspace/:/var/www/html/